server:
  port: 8081

security:
  oauth2:
    client:
      client-id: my-client
      client-secret: secretpassword
      user-authorization-uri: http://localhost:8081/user
      client-authentication-scheme: form
      scope: webclient 
      grant-type: password

    resource:
      token-info-uri: http://localhost:8081/oauth/token